name: Build

on: [ push ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to registry
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the image
      run: |
        docker build . --file Dockerfile --tag deployer
    - name: Tag the image
      run: |
        docker tag deployer matthewbaggett/docker-deploy-webhook:latest
        docker tag deployer docker.pkg.github.com/matthewbaggett/docker-deploy-webhook/deployer:latest
    - name: Publish image to Registry
      run: |
        docker push matthewbaggett/docker-deploy-webhook:latest
        docker push docker.pkg.github.com/matthewbaggett/docker-deploy-webhook/deployer:latest
